### ISSUE TITLE
Trying to run stops_freq with missing direction_id crashes Pandas

### ISSUE THREAD

**Issue by Rikuoja** [Bondify/gtfs_functions#10]
Some gtfs feeds (e.g. Estonia, http://peatus.ee/gtfs/gtfs.zip ) have missing direction_ids.

While the previous PR #9 fixes import_gtfs in those cases, stops_freq function still crashes if direction_id is missing.

Will make a PR to fix this too.

**Comment by Bondify** [comment]
hi @Rikuoja thanks for input. The newest version of the package should fix this. Please let me know if that's not the case.
