### ISSUE TITLE
Issue with cut_gtfs function in segment_gdf

### ISSUE THREAD

**Issue by MvdW123** [Bondify/gtfs_functions#11]
I am trying to run this code with the GTFS data as you used but get a UnboundLocalError when trying to run segment_gdf. It says that in line 508 of gtfs_functions last_point is referenced before assignment. Please advise on how to resolve this issue. Thanks :)

**Comment by jnh277** [comment]
Hi, I've also had this problem, did you solve it?

**Comment by MvdW123** [comment]
No I haven't yet, working on a solution, any insights would be great!

**Comment by jnh277** [comment]
When i filtered the gtfs file down to only bus routes this function then ran for me, so maybe it is something to do with a difference between bus and other routes types. I have also been making a similar version to the cut segment function that does not extract the shape data as this is then a whole lot faster and I don't think she shape data is always needed. Perhaps I can share this back

**Comment by MvdW123** [comment]
That sounds very possible, how did you filter the data to isolate the bus routes? If its too hard to explain maybe you could attach the filtered data that ran for you? Thanks

**Comment by jnh277** [comment]
buy routes have route type in the seven hundreds so i used the following code 

`
bus_routes = routes.loc[(routes.route_type>=700) & (routes.route_type<800)].reset_index()
`

**Comment by MvdW123** [comment]
That's perfect, but my dataset still runs into trouble as the shapes, stops and stop_times data frames still includes all of the various modes of transport. How does one remove these unwanted modal data points from all of the data frames?

**Comment by jnh277** [comment]
ahh yep sorry here is the rest

`
# we can cut down the trips based on the route ids
sydney_bus_trips = trips.loc[trips.route_id.isin(sydney_bus_route_ids)]     # this has shape id

# can cut down stop_times based on trip id
sydney_bus_stop_times = stop_times.loc[stop_times.trip_id.isin(sydney_bus_trips['trip_id'])]

# can cut down stops based on stop id from stop times
sydney_bus_stops = stops.loc[stops.stop_id.isin(sydney_bus_stop_times['stop_id'])]

# cut down shapes based on shape id from above
sydney_bus_shapes = shapes.loc[shapes.shape_id.isin(sydney_bus_trips['shape_id'])]
`

**Comment by TheJAG** [comment]
I've done some digging on the Sydney ferry GTFS network where this problem occurs. What happens is when looking for the first segment to cut, it can't find a result. Hence in the subsequent middle segment searches the `last_point` is not set and the `referenced before assignment` error occurs.

The reason for this is that the line that gets created to cut the shapes does not intersect with the shapes. See image below.

![image](https://user-images.githubusercontent.com/1350370/163064535-df1dd262-db1b-4ca5-8001-2dd9049b2adf.png)

A fairly simple solution I can see is to apply a very small buffer to the segments. This will now result in an intersection for the first segment.

i.e.
`511:            if segment.buffer(0.00001).intersects(cut_lines[0]):`
(same on line 532 and 595)

@Bondify I'm happy to create a pull request for this, just need collaborator rights.

**Comment by praneethd7** [comment]
This works great! Thanks a lot @TheJAG!
