### ISSUE TITLE
IndexError when use gtfs.line_freq

### ISSUE THREAD

**Issue by cla93** [Bondify/gtfs_functions#12]
When I try

```
line_freq = gtfs.lines_freq(stop_times, trips, shapes, routes, cutoffs = cutoffs)
```
I get the following error
``IndexError: index 0 is out of bounds for axis 0 with size 0``

This happens also with ```gtfs.cut_gtfs(stop_times, stops, shapes)```
And with or without the ``cutoffs`` variable in input
I tried it with different gtfs files, but the result is always the same

**Comment by Bondify** [comment]
please check if the error persists with the latest version of the package @cla93
