### ISSUE TITLE
No attribute 'ntrips' when calculating line frequencies. What is missing in my feed?

### ISSUE THREAD

**Issue by norgepab** [Bondify/gtfs_functions#18]
<img width="900" alt="Screen Shot 2023-03-24 at 5 36 58 PM" src="https://user-images.githubusercontent.com/102338575/227646099-5dd32f85-a7df-4dee-95a9-1667b3920eb4.png">

**Comment by Bondify** [comment]
@norgepab this should be fixed in the newest version. Thanks for reporting the issue
