### ISSUE TITLE
'DataFrame' object has no attribute 'append'

### ISSUE THREAD

**Issue by Kittu511** [Bondify/gtfs_functions#21]
'DataFrame' object has no attribute 'append' error for avg_speeds and segments_freq.

**Comment by WohlstadterEWG** [comment]
It appears that the dataframe append method was deprecated and subsequently removed.  (see https://github.com/pandas-dev/pandas/issues/35407)

**Comment by WohlstadterEWG** [comment]
Both avg_speeds and segments_freq run if you downgrade pandas to 1.5.3
`conda install pandas=1.5.3`

**Comment by Bondify** [comment]
hi @WohlstadterEWG this problem should be fixed in the latest version. Please update and try again. Feel free to re-open the issue if you see that the problem persists
