### ISSUE TITLE
module 'pendulum' has no attribute 'period'

### ISSUE THREAD

**Issue by philam** [Bondify/gtfs_functions#36]
It seems that a [new version](https://github.com/sdispater/pendulum/releases) of the pendulum module has been released (3.0) which is breaking something in the code.

When I tried running `stop_freq` (running a conda env with Python 3.8) I got the error:

`AttributeError: module 'pendulum' has no attribute 'period'`

I fixed this temporarily by installing the 2.1.2 version of pendulum.

Some more information here that I found when researching the issue: https://github.com/dagster-io/dagster/discussions/18783

Thanks!

**Comment by Bondify** [comment]
hi @philam thanks for raising this issue. This problem should be solve from version 2.3.0 onwards.
