### ISSUE TITLE
Segment Level Speeds Question

### ISSUE THREAD

**Issue by d-wasserman** [Bondify/gtfs_functions#6]
Hi ! 
First, this is a great and useful resource for exploring GTFS dataset. Thanks for the great work on this. 

Second, for segment level speeds, are you look at speeds in terms of the gaps between departures and the next arrival times? From the code, I think the answer is yes, but I wanted to get a creator definition of how "run-time" speeds are defined for clarification. I am asking because I want to make sure that time "waiting" at stops, is or is not incorporated into the speed calculation. 

Thanks!

David

**Comment by Bondify** [comment]
hi David, sorry for the very late response. You are right, waiting times at the stops are not taken into account. Mostly because most GTFS feeds have the same values for `arrival_time` and `departure_time` not accounting for dwell times at stops.
